web/router.ex
defmodule Triage.Router do
  use Triage.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Triage do
    pipe_through :browser # Use the default browser stack

    get "/", ProjectController, :index
    resources "/projects", ProjectController do
      get "/triage", ProjectController, :triage
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Triage do
  #   pipe_through :api
  # end
end

lib/mix/tasks/triage.update.ex
defmodule Mix.Tasks.Triage.Update do
  use Mix.Task
  alias Triage.Project

  @shortdoc "Update pull request and issue counts"

  def run(_args) do
    Mix.Task.run "app.start"
    Mix.shell.info "Updating counts"
    client_key = System.get_env("GITHUB_API_KEY")
    client = Tentacat.Client.new(%{access_token: client_key})

    for project <- Triage.Repo.all(Project) do
      # Mix.shell.info "Getting count for #{project.organization}/#{project.name}"
      all = Project.open_issues(project, client)
      pulls = all |> Project.pull_requests |> length
      issues = all |> Project.not_prs |> length
      untriaged = all |> Project.not_prs |> Project.untriaged |> length
      # Mix.shell.info "Count is #{pulls} Pull Requests and #{issues} Issues"
      Triage.Repo.insert!(Ecto.build_assoc(project, :states, %{issues: issues, untriaged_issues: untriaged, pull_requests: pulls}))
    end
  end
end

lib/triage/endpoint.ex
defmodule Triage.Endpoint do
  use Phoenix.Endpoint, otp_app: :triage

  socket "/socket", Triage.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :triage, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_triage_key",
    signing_salt: "vIcq2fDH"

  plug Triage.Router
end

lib/triage/repo.ex
defmodule Triage.Repo do
  use Ecto.Repo, otp_app: :triage
end

web/models/project.ex
defmodule Triage.Project do
  use Triage.Web, :model

  schema "projects" do
    field :name, :string
    field :organization, :string
    field :triaged_at, Ecto.DateTime

    has_many :states, Triage.State
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :organization, :triaged_at])
    |> validate_required([:name, :organization])
  end

  def open_issues(prj, client) do
    Tentacat.Issues.list(prj.organization, prj.name, client)
  end

  def not_prs(issues) do
    Enum.filter(issues, fn(x) -> Map.get(x, "pull_request") == nil end )
  end

  def pull_requests(issues) do
    Enum.filter(issues, fn(x) -> Map.get(x, "pull_request") != nil end )
  end

  def untriaged(issues) do
    Enum.filter(issues, fn(x) -> Map.get(x, "milestone") == nil end )
  end

end

web/models/state.ex
defmodule Triage.State do
  use Triage.Web, :model

  schema "states" do
    field :issues, :integer
    field :untriaged_issues, :integer
    field :pull_requests, :integer
    belongs_to :project, Triage.Project

    timestamps()
  end

  @required ~w(issues untriaged_issues pull_requests)

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required)
    |> validate_required(@required)
  end
end

web/controllers/page_controller.ex
defmodule Triage.PageController do
  use Triage.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/project_controller.ex
defmodule Triage.ProjectController do
  use Triage.Web, :controller

  alias Triage.Project

  def index(conn, _params) do
    projects = Repo.all(Project)
                |> Repo.preload(states: from(s in Triage.State, order_by: [desc: s.inserted_at]))
    render(conn, "index.html", projects: projects)
  end

  def new(conn, _params) do
    changeset = Project.changeset(%Project{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"project" => project_params}) do
    changeset = Project.changeset(%Project{}, project_params)

    case Repo.insert(changeset) do
      {:ok, _project} ->
        conn
        |> put_flash(:info, "Project created successfully.")
        |> redirect(to: project_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    project = Repo.get!(Project, id)
              |> Repo.preload(states: from(s in Triage.State, order_by: [desc: s.inserted_at], limit: 1))
    render(conn, "show.html", project: project)
  end

  def edit(conn, %{"id" => id}) do
    project = Repo.get!(Project, id)
    changeset = Project.changeset(project)
    render(conn, "edit.html", project: project, changeset: changeset)
  end

  def triage(conn, %{"project_id" => id }) do
    project = Repo.get!(Project, id)
    changeset = Project.changeset(project, %{triaged_at: Ecto.DateTime.utc})
    case Repo.update(changeset) do
      {:ok, _project} ->
        conn
        |> put_flash(:info, "Updated triage time for #{project.organization}/#{project.name}")
        |> redirect(to: project_path(conn, :index))
      {:error, _cs} ->
        conn
        |> put_flash(:info, "Failed to set triage time for #{project.organization}/#{project.name}")
    end
  end

  def update(conn, %{"id" => id, "project" => project_params}) do
    project = Repo.get!(Project, id)
    changeset = Project.changeset(project, project_params)

    case Repo.update(changeset) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project updated successfully.")
        |> redirect(to: project_path(conn, :show, project))
      {:error, changeset} ->
        render(conn, "edit.html", project: project, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    project = Repo.get!(Project, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(project)

    conn
    |> put_flash(:info, "Project deleted successfully.")
    |> redirect(to: project_path(conn, :index))
  end
end

web/views/error_view.ex
defmodule Triage.ErrorView do
  use Triage.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Triage.LayoutView do
  use Triage.Web, :view
end

web/views/page_view.ex
defmodule Triage.PageView do
  use Triage.Web, :view
end

web/views/project_view.ex
defmodule Triage.ProjectView do
  use Triage.Web, :view

  def state(project) do
    case project.states do
      [ state | _tail ] -> state
      _ -> 0
    end
  end

  def issue_url(project, triaged \\ false) do
    triage = if triaged do
      "+no%3Amilestone"
    else
      ""
    end
    "https://github.com/#{project.organization}/#{project.name}/issues?q=is%3Aopen+is%3Aissue+sort%3Aupdated-asc#{triage}"
  end
  
  def pr_url(project) do
    "https://github.com/#{project.organization}/#{project.name}/pulls?q=is%3Aopen+is%3Apr+sort%3Aupdated-asc"
  end
  
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Chef Triage!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/project/edit.html.eex
<h2>Edit project</h2>

<%= render "form.html", changeset: @changeset,
                        action: project_path(@conn, :update, @project) %>

<%= link "Back", to: project_path(@conn, :index) %>

web/templates/project/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :organization, class: "control-label" %>
    <%= text_input f, :organization, class: "form-control" %>
    <%= error_tag f, :organization %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/project/index.html.eex
<h2>Chef Project Triage</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Organization</th>
      <th>Last triage</th>
      <th>All Issues</th>
      <th>Untriaged Issues</th>
      <th>Pull Requests</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for project <- @projects do %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.organization %></td>
      <td><%= project.triaged_at %></td>
      <%= if project.states != [] do %>
      <td><a href=<%= issue_url(project, false) %> target="_blank"><%= state(project).issues %></a></td>
      <td><a href=<%= issue_url(project, true) %> target="_blank"><%= state(project).untriaged_issues %></a></td>
      <td><a href=<%= pr_url(project) %> target="_blank"><%= state(project).pull_requests %></a></td>
      <% else %>
        <td>Not yet checked!</td>
      <% end %>

      <td class="text-right">
        <%= link "Triage Now!", to: project_project_path(@conn, :triage, project), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New project", to: project_path(@conn, :new) %>

web/templates/project/new.html.eex
<h2>New project</h2>

<%= render "form.html", changeset: @changeset,
                        action: project_path(@conn, :create) %>

<%= link "Back", to: project_path(@conn, :index) %>

web/templates/project/show.html.eex
<h2>Show project</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @project.name %>
  </li>

  <li>
    <strong>Organization:</strong>
    <%= @project.organization %>
  </li>

  <li>
    <strong>Last triage:</strong>
    <%= @project.last_triage %>
  </li>

</ul>

<%= link "Edit", to: project_path(@conn, :edit, @project) %>
<%= link "Back", to: project_path(@conn, :index) %>